# create a lastest version mysql server container

# docker-compose up -d

version: "3.8"

services:
  db:
    env_file: .env
    image: mysql
    container_name: mysql_trybe
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MY_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - /home/hfreitas/Documents/projects/docker/volumes/mysql:/var/lib/mysql
